# Generated by Django 3.0.3 on 2020-02-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closingDate', models.DateField()),
                ('openingDate', models.DateField()),
                ('description', models.TextField()),
                ('noOfStock', models.IntegerField()),
                ('approved', models.BooleanField()),
                ('sells', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buys', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessowner.Businessowner')),
            ],
        ),
    ]
