# Generated by Django 3.0.3 on 2020-03-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200305_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
