# Generated by Django 3.0.3 on 2020-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
