# Generated by Django 3.1.3 on 2020-11-28 11:00

import admina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admina',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=admina.models.user_directory_path),
        ),
    ]
