# Generated by Django 3.1.3 on 2020-12-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admina', '0003_auto_20201130_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admina',
            name='sex',
        ),
    ]
