# Generated by Django 3.1.3 on 2020-11-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessowner', '__first__'),
        ('investor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessowner.businessowner')),
                ('investorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
        ),
    ]
