# Generated by Django 3.1.3 on 2020-11-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='businessId',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='investorId',
            new_name='investor',
        ),
    ]
