# Generated by Django 3.1.3 on 2020-11-21 02:28

import businessowner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='legality',
            field=models.ImageField(blank=True, null=True, upload_to=businessowner.models.user_directory_path),
        ),
    ]
