# Generated by Django 3.1.3 on 2020-11-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0002_auto_20201121_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='is_valid_account',
            field=models.CharField(choices=[('PA', 'Pending Approval'), ('AP', 'Approved'), ('DE', 'Declined'), ('PU', 'Pending Update')], default='PA', max_length=2),
        ),
    ]
