# Generated by Django 3.1.3 on 2020-11-28 11:00

import businessowner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0003_auto_20201125_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=businessowner.models.user_directory_path),
        ),
    ]
