# Generated by Django 3.1.3 on 2020-12-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0005_auto_20201130_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
