# Generated by Django 3.1.3 on 2020-11-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201127_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phoneNo',
            new_name='phone_no',
        ),
    ]
