# Generated by Django 3.1.3 on 2020-11-28 06:54

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201127_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='sex',
        ),
        migrations.AddField(
            model_name='account',
            name='account_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(default='Addis Ababa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
