# Generated by Django 3.1.3 on 2020-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(default='middlename', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.CharField(default='Female', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
