# Generated by Django 3.0.3 on 2020-02-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
        ('businessowner', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStockLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numberOfStock', models.IntegerField()),
                ('investorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investor.Investor')),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businessowner.Businessowner')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.Stock')),
            ],
        ),
    ]
