# Generated by Django 3.1.3 on 2020-11-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '__first__'),
        ('businessowner', '0001_initial'),
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldStockLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numberOfStock', models.IntegerField()),
                ('investorId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investor.investor')),
                ('sellerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businessowner.businessowner')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stock')),
            ],
        ),
    ]
