# Generated by Django 3.1.3 on 2020-11-28 11:00

from django.db import migrations, models
import investor.models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_auto_20201128_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=investor.models.user_directory_path),
        ),
    ]
