# Generated by Django 3.1.3 on 2020-11-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_investor_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='last_name',
        ),
    ]
