# Generated by Django 3.1.3 on 2020-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_auto_20201130_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='nationality',
            new_name='investor_nationality',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='sex',
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_driving_licence_ID',
            field=models.CharField(default='lfdksj', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_kebele',
            field=models.CharField(default='12/13', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_kebele_ID',
            field=models.CharField(default='fljsk', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_occupation',
            field=models.CharField(default='software engineer', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_passport_number',
            field=models.CharField(default='EP323233', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_driving_licence_ID',
            field=models.CharField(default='lfskd', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_first_name',
            field=models.CharField(default='firstnae', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_house_no',
            field=models.CharField(default='houseno', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_kebele',
            field=models.CharField(default='12/12', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_kebele_ID',
            field=models.CharField(default='2332', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_last_name',
            field=models.CharField(default='lastname', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_middle_name',
            field=models.CharField(default='middlename', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_occupation',
            field=models.CharField(default='occ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_passport_number',
            field=models.CharField(default='lskfd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_phone_no',
            field=models.CharField(default='dlks', max_length=10),
            preserve_default=False,
        ),
    ]
