# Generated by Django 3.1.3 on 2020-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_auto_20201201_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investor_house_no',
            field=models.CharField(default='567', max_length=20),
            preserve_default=False,
        ),
    ]
