# Generated by Django 3.1.3 on 2020-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0006_investor_investor_house_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='investor_kebele_ID',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='respondent_kebele_ID',
        ),
        migrations.AddField(
            model_name='investor',
            name='investor_resident_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investor',
            name='respondent_resident_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_driving_licence_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_house_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investor_passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='respondent_driving_licence_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='respondent_house_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='respondent_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='respondent_passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
