# Generated by Django 3.0.3 on 2020-02-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('reportCount', models.IntegerField()),
                ('reportedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportedByUserId', to='investor.Investor')),
                ('reportedUserId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reportedUserId', to='investor.Investor')),
            ],
        ),
    ]
