# Generated by Django 3.1.3 on 2020-12-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreport', '0003_auto_20201204_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='report_status',
            field=models.CharField(choices=[('WS', 'Warning Sent'), ('PR', 'Pending Resolve')], default='PR', max_length=2),
        ),
    ]
