# Generated by Django 3.1.3 on 2020-11-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
        ('businessowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businessowner.businessowner')),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investor.investor')),
            ],
        ),
    ]
