# Generated by Django 3.1.3 on 2020-11-21 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='investor',
        ),
        migrations.AddField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='account.account'),
            preserve_default=False,
        ),
    ]
