# Generated by Django 3.1.3 on 2020-11-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20201121_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='account',
            new_name='commentedBy',
        ),
    ]
